#!/bin/bash
echo "IMPORTANT!"
echo "The certificates generated by this script are NOT secure and should be used for testing only. For a detailed account"
echo "on how to securely generate self-signed certificates and secure your server, read this article:"
echo "https://jamielinux.com/docs/openssl-certificate-authority/introduction.html"

echo "Checking for openSSL..."
OPEN_SSL=`which openssl`
if [ "$OPEN_SSL" == "" ]; then
    echo "Not found. OpenSSL is required to generate the certificates. Install openssl and then run this script again"
    exit
else
    echo "Ok"
fi
echo "Generating Certificate Authority"
$OPEN_SSL genrsa -out config/ca.key.pem 2048 2>/dev/null
$OPEN_SSL req -new -x509 -key config/ca.key.pem -days 3650 -out config/ca.cert.pem -subj "/C=ZA/ST=Gauteng/L=Johannesburg/O=RPC_Crypto/OU=CA/CN=CA"
echo "Generating server certificate"
$OPEN_SSL genrsa -out config/server.key.pem 2048 2>/dev/null
$OPEN_SSL req -new -sha256 -key config/server.key.pem -out config/server.csr -subj "/C=ZA/ST=Gauteng/L=Johannesburg/O=RPC_Crypto/OU=server/CN=localhost"
$OPEN_SSL x509 -req -days 365 -in config/server.csr -CA config/ca.cert.pem -CAkey config/ca.key.pem -set_serial 01 -out config/server.crt
rm config/server.csr
echo "Generating client certificate..."
$OPEN_SSL genrsa -out config/client.key.pem 2048 2>/dev/null
$OPEN_SSL req -new -key config/client.key.pem -out config/client.csr -subj "/C=ZA/ST=Johannesburg/O=RPC-Crypto/OU=client/CN=localhost"
$OPEN_SSL x509 -req -days 365 -in config/client.csr -CA config/ca.cert.pem -CAkey config/ca.key.pem -set_serial 01 -out config/client.crt
rm config/client.csr
